### ISSUE TITLE
Question: Where is the data folder?

### ISSUE THREAD

**Issue by serhattsnmz** [handshake-org/hnsd#117]
I am using hnsd as docker container and everytime I restart the container, the blocks are downloaded again. 

I wonder where it downloads the data of blocks and if it is possible to bind it as volume? 

Thanks.

**Comment by rithvikvibhu** [comment]
From the README:

>Recommended usage:

>```sh
>mkdir ~/.hnsd
>hnsd -t -x ~/.hnsd
>```
>This will start hnsd sync from the hard-coded checkpoint and continue to save its own checkpoints to disk to ensure rapid chain sync on future boots.

Not sure exactly how that fits in with mounting volumes with Docker, maybe try passing in the mounted path to the `-x` argument.
