### ISSUE TITLE
Failed to set capabilities on file

### ISSUE THREAD

**Issue by antoinemcgrath** [handshake-org/hnsd#13]
When attempting the following segment of a Linux install:
`sudo setcap 'cap_net_bind_service=+ep' /path/to/hnsd`

The responding error is delivered:
_Failed to set capabilities on file ` /path/to/hnsd' (Invalid argument)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file_

It could be that not all linux kernals (I'm running 4.4.0-57-generic) support setcap [ https://serverfault.com/a/874053](https://serverfault.com/a/874053)

**Comment by antoinemcgrath** [comment]
Any help on this would be appreciated.

**Comment by hschoenburg** [comment]
Oh wow this is old. You need to set the path to your hnsd install. Right now your command includes `path/to/hnsd` this needs to be the actual path to the compiled executable created by the make command. Should be the root dir of the install.
