### ISSUE TITLE
Rust rewrite?

### ISSUE THREAD

**Issue by Bajix** [handshake-org/hnsd#17]
Hi I was curious if the Handshake org ever considered rebuilding this in Rust? Performance wise, they're virtually identical, with C only be slightly faster due to lack of bounds checking. Rust however has many safety guarantees that C doesn't have: all compiled safe Rust code is guaranteed to be memory & thread safe, and devoid of seg faults. Given this emphasis correctness & security, it seems like a more suitable language choice. Rust also makes it easier to optimize concurrency, often making it viable to build concurrent solutions that are more performant than a C/C++ counterpart lacking concurrency optimizations (Read up on the story of Stylo/Firefox Quantum).  Has the team considered making a Rust version of Handshake?

**Comment by pinheadmz** [comment]
There is a Rust implementation of the hsd full node in progress at: https://github.com/UrkelLabs/rsd

If you feel like contributing, that would be a good place to start!

**Comment by jacobhaven** [comment]
I'm considering a Go (or maybe just [Cgo](https://golang.org/cmd/cgo/)) version of this light name resolution to use as a plugin for [CoreDNS](https://github.com/coredns/coredns).

**Comment by Bajix** [comment]
@jacobhaven Probably would be easiest to do a cgo version at present. Have you considered rewriting CoreDNS with Rust? Besides the obvious strengths in terms of correctness, provably correct concurrency / threading, performance and build output size, Rust could be specifically of interest to CoreDNS for enabling some really creative and powerful memory optimizations. For instance, you could have a buffer of an incoming packet that you then parse iteratively, such that each time you return a new intermediary struct that references slices of the original buffer; optimally this means it's viable to build using zero dynamic allocations. I think there are a couple of projects that I've heard about that do things like this, super interesting stuff.

**Comment by pinheadmz** [comment]
Closing for now -- looking forward to this contribution in the future!
