### ISSUE TITLE
Test Framework

### ISSUE THREAD

**Issue by tynes** [handshake-org/hnsd#23]
It would be ideal to add unit tests to `hnsd` so that its easier to develop without regressions. There are many options for test frameworks in C, many projects opt to roll their own framework. I found what I believe to be good options.

### Options

- [cmocka](https://cmocka.org/)
  - Used by bind, libssh
  - [Custom assertions](https://api.cmocka.org/group__cmocka__asserts.html)
  - Simple to use, create an array of `CMUnitTest`s using `cmocka_unit_test` which wrap `describe` like functions

- [check](https://libcheck.github.io/check/doc/check_html/index.html#Top)
  - Designed to work with autotools
  - Simple, but a lot of boilerplate

- [CGreen](https://cgreen-devs.github.io/index.html#_cgreen_quickstart_guide)
  - Large, has many features
  - TDD/BDD support, along with `Before`, `After`, etc macros

- Custom
  - No extra dependencies
  - As simple as it needs to be
  - Must implement it, must be bugfree

----

I'd personally opt for using `cmocka` since it looks simple to use and is also used by other applications that are similar (DNS + security). It would be easier than creating our own custom test library.

**Comment by pinheadmz** [comment]
We could use CI in the hsd repo too, CircleCI can install hnsd and we run it as a child_process with nodejs and run bmocha e2e tests.

**Comment by tynes** [comment]
> We could use CI in the hsd repo too, CircleCI can install hnsd and we run it as a child_process with nodejs and run bmocha e2e tests. Tried a similar thing w bcoin: [bcoin-org/bcoin#759](https://github.com/bcoin-org/bcoin/pull/759)

That would be good for integration tests, I am thinking more along the idea of unit tests here. Unit tests would be useful in particular for the resource serialization.

**Comment by pinheadmz** [comment]
Made some progress in https://github.com/handshake-org/hnsd/pull/68 and expanded in https://github.com/handshake-org/hnsd/pull/76 but it might be nice to import one of these existing frameworks in the future.
