### ISSUE TITLE
hnsd on iOS

### ISSUE THREAD

**Issue by agrinman** [handshake-org/hnsd#27]
Hi there -- I'd like to build a handshake dns resolver on iOS. I am wondering if someone here could guide me in the right direction:
(1) are there instructions somewhere for building this (or a library version of hnsd) for an iOS target?
(2) is there a function that takes an input query (in DNS-wire format) and returns a response (also in DNS-wire format)?

Thanks!

**Comment by boymanjor** [comment]
@agrinman hello, and thanks for your interest in the project! Currently, `hnsd` is not compatible with the latest, Handshake p2p network protocol. We're considering a complete rewrite of the codebase, in lieu of patch. I would recommend watching this repo for development updates and kick starting your project once we regain compatibility. I would also recommend joining the developer Telegram chat: https://t.me/hns_tech. I believe there has already been discussion on iOS support for Handshake, in general. 

> (1) are there instructions somewhere for building this (or a library version of hnsd) for an iOS target?
(2) is there a function that takes an input query (in DNS-wire format) and returns a response (also in DNS-wire format)?

`hnsd` cannot be compiled as a library, and does not expose any functions. It was originally written as a daemon only. In the event of a rewrite, I'm not sure if this will change.

**Comment by pinheadmz** [comment]
Closing for now, @agrinman I hope you are still interested in working on this!
