### ISSUE TITLE
Mainnet

### ISSUE THREAD

**Issue by pinheadmz** [handshake-org/hnsd#33]
There's a lot to review:

#29 #30 #31 #32 

If you're feeling crazy and just want to compile the whole mess and get started using hnsd on mainnet, you can attempt to deploy my combined branch: https://github.com/pinheadmz/hnsd/tree/maintest1

I'm running it right now as my computer's only resolver! It's holding up great, and I'm able to browse to all the dope HNS websites users have developed so far ;-)

**Comment by codaelux** [comment]
running as my only resolver currently works as expected
