### ISSUE TITLE
unknown command: 6

### ISSUE THREAD

**Issue by pinheadmz** [handshake-org/hnsd#56]
This message can be safely ignored.

What's happening is `hnsd` is connecting to `hsd` full nodes, which are being very nice and offering to send unconfirmed transaction messages (`INV`) they don't realize `hnsd` does not have a mempool and so these messages are just ignored.

We can probably fix this on either `hnsd` or `hsd` by enabling a blocks-only mode (Bitcoin Core has this)

The actual number `6` comes from [the hsd protocol message list](https://github.com/handshake-org/hsd/blob/a94ce87a886e943a68d4a3e67068f6e473c21156/lib/net/packets.js#L46):

```js
/**
 * Packet types.
 * @enum {Number}
 * @default
 */

exports.types = {
  VERSION: 0,
  VERACK: 1,
  PING: 2,
  PONG: 3,
  GETADDR: 4,
  ADDR: 5,
  INV: 6,
  GETDATA: 7,
  NOTFOUND: 8,
  GETBLOCKS: 9,
  GETHEADERS: 10,
  HEADERS: 11,
  SENDHEADERS: 12,
  BLOCK: 13,
  TX: 14,
  REJECT: 15,
  MEMPOOL: 16,
  FILTERLOAD: 17,
  FILTERADD: 18,
  FILTERCLEAR: 19,
  MERKLEBLOCK: 20,
  FEEFILTER: 21,
  SENDCMPCT: 22,
  CMPCTBLOCK: 23,
  GETBLOCKTXN: 24,
  BLOCKTXN: 25,
  GETPROOF: 26,
  PROOF: 27,
  CLAIM: 28,
  AIRDROP: 29,
  UNKNOWN: 30,
  // Internal
  INTERNAL: 31,
  DATA: 32
};
```

By contrast, the `hnsd` protocol message list is much shorter:

https://github.com/handshake-org/hnsd/blob/1b47849f48f0a8a380e7753204ef25f88ca0a3c4/src/msg.h#L13-L24

**Comment by tuxcanfly** [comment]
Maybe we could silence this log and make it only appear when `HSK_DEBUG_LOG` is set.

**Comment by nodar-chkuaselidze** [comment]
Blocks only mode can be good fix for this issue.

I believe it's useful to reduce(hopefully fully clean up) `Unknown command`s.

**Comment by tuxcanfly** [comment]
Isn't there a service flag for blocks only? Maybe hnsd can set it when doing handshake.

**Comment by pinheadmz** [comment]
I don't think bcoin/hsd have this feature like Bitcoin Core does.

**Comment by tuxcanfly** [comment]
https://github.com/handshake-org/hnsd/blob/master/src/msg.c#L417

It seems that Core uses these bits for determining if it's going to relay transactions or not. Maybe if we set this and peers understand it, they won't bother us? Since we're not going to be relaying anyway...

**Comment by pinheadmz** [comment]
oh you're totally right! In fact:

https://github.com/handshake-org/hsd/blob/master/lib/net/peer.js#L613-L616

I am completely wrong, hsd SPV nodes signal this already

**Comment by pinheadmz** [comment]
@tuxcanfly i think you got it, try switching false to true I bet thats all we need.

**Comment by tuxcanfly** [comment]
Awesome, glad to hear that. And an F for all the bandwidth wasted so far.... just kidding :smile:

**Comment by pinheadmz** [comment]
I miss u

**Comment by tuxcanfly** [comment]
Awesome, no unknown commands so far with `no_relay = true`. So this works huh? :sweat_smile:

**Comment by tuxcanfly** [comment]
Thanks  @nodar-chkuaselidze for reminding about blocks only mode :smile:

**Comment by nodar-chkuaselidze** [comment]
I believe it was @pinheadmz, but u're welcome <3 :D
