### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by hschoenburg** [handshake-org/hnsd#6]
With hskd up and running on defaults `$ ./bin/hskd`

I start hns with
` $ ./hnsd --pool-size=1 --rs-host=127.0.0.1:53`

and get
```
chain (0): chain is fully synced

addrman: added addr: 127.0.0.1:15038

pool: pool opened (size=1)

ns: root nameserver listening on: 127.0.0.1:35359

rs: recursive nameserver pointing to: 127.0.0.1@35359

failed opening rns: EFAILURE

peer 0 (127.0.0.1:15038): closing peer

```

**Comment by kfichter** [comment]
Having this issue as well. Did you end up solving this?

**Comment by pkrasam** [comment]
I am getting this error too when attempting to "Run a Light Resolver (HNSD)"

$ ./hnsd --pool-size=1 --rs-host=127.0.0.1:53
addrman: added addr: 172.104.214.189:13038
addrman: added addr: 173.255.209.126:13038
addrman: added addr: 172.104.177.177:13038
addrman: added addr: 139.162.183.168:13038
pool: pool opened (size=1)
ns: root nameserver listening on: 127.0.0.1:15359
rs: recursive nameserver pointing to: 127.0.0.1@15359
failed opening rns: EFAILURE
peer 0 (172.104.177.177:13038): closing peer
