### ISSUE TITLE
Short of public full nodes?

### ISSUE THREAD

**Issue by befranz** [handshake-org/hnsd#77]
With the growing amount of apps which uses hnsd it seems we need more public full nodes to get the data from. I run one myself with max-inbound=500 and it comes to this limit soon.

I'm not sure if I understand this correctly but if I say ideally an spv node should have 4 full nodes to connect with, then the sum of max-inbound of all public full nodes should be 1/4 of all running spv nodes out there, right?

**Comment by Falci** [comment]
[Parking](http://parking.sinpapeles) has a public hsd node: 
```ajpbuxkwtf7hkwbpw27siwg6dylsly4743rbhy2jssb3rxmircbrs@45.79.216.182```

**Comment by rithvikvibhu** [comment]
[Handshake Tools](https://htools.work/) public node:
`aplie5zadqqlghqvbq7by4i4ce7rngenwyxhmiq4byzv6svnqd5b2@138.197.52.107`
