### ISSUE TITLE
Failed to set capabilities

### ISSUE THREAD

**Issue by Nanashi-B** [handshake-org/hnsd#97]
when i run this command :

setcap 'cap_net_bind_service=+ep' /hnsd

i have this message : 

Failed to set capabilities on file `/hnsd' (No such file or directory)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file

**Comment by pinheadmz** [comment]
Did you actually install hnsd in your systems root directory? `/hnsd` is an absolute path

**Comment by Nanashi-B** [comment]
oh yes sorry it's an error but even when the path is right it didn't work
![image](https://user-images.githubusercontent.com/65498155/187506678-4e8cfa65-52e5-4c81-b514-59661ab56575.png)

**Comment by pinheadmz** [comment]
If you execute /opt/hnsd ... the program runs normally?

**Comment by Nanashi-B** [comment]
like that ?

![image](https://user-images.githubusercontent.com/65498155/187507491-eedbfb57-6340-45d6-aa46-650e6f78f637.png)

**Comment by pinheadmz** [comment]
have you been able to run hnsd at all? Do you know the exact path of the executable?
